# Sample workflow for building and deploying a Nuxt site to GitHub Pages
# To get started with Nuxt see: https://nuxtjs.org/docs/get-started/installation
name: Deploy Nuxt site to Pages

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [content-updated]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout private blog content
        uses: actions/checkout@v4
        with:
          repository: WorldWideHisa/wwh-blog-content
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: ./content
          clean: true

      - name: Remove README files and templates from content
        run: |
          find ./content -name "README.md" -delete
          rm -rf ./content/articles/template/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      # - name: Setup Pages
      #   uses: actions/configure-pages@v5
      #   with:
      #     static_site_generator: nuxt
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .ouput/public
            .nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('.ouput/public') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-
      - name: Install dependencies
        run: npm ci
      - name: Static HTML export with Nuxt
        run: npm run generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
